import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
  },
  options: { typeAware: true, typeCheck: true },
  plugins: ["eslint", "import", "oxc", "react", "typescript"],
  rules: {
    "eslint/array-callback-return": "warn",
    "eslint/arrow-body-style": ["warn", "never"],
    "eslint/curly": "warn",
    "eslint/default-case": "warn",
    "eslint/default-case-last": "error",
    "eslint/eqeqeq": ["warn", "smart"],
    "eslint/eslint/getter-return": "error",
    "eslint/no-array-constructor": "warn",
    "eslint/no-caller": "error",
    "eslint/no-duplicate-imports": "off", // `import/no-duplicates`を使用する。
    "eslint/no-eval": "error",
    "eslint/no-extend-native": "error",
    "eslint/no-extra-bind": "warn",
    "eslint/no-extra-label": "warn",
    "eslint/no-implied-eval": "error",
    "eslint/no-iterator": "error",
    "eslint/no-label-var": "error",
    "eslint/no-lone-blocks": "warn",
    "eslint/no-loop-func": "error",
    "eslint/no-multi-str": "error",
    "eslint/no-new-func": "error",
    "eslint/no-new-wrappers": "error",
    "eslint/no-proto": "error",
    "eslint/no-restricted-globals": "error",
    "eslint/no-script-url": "error",
    "eslint/no-self-compare": "error",
    "eslint/no-sequences": "error",
    "eslint/no-template-curly-in-string": "warn",
    "eslint/no-throw-literal": "error",
    "eslint/no-unreachable-loop": "error",
    "eslint/no-unused-expressions": [
      "error",
      { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true },
    ],
    "eslint/no-unused-vars": [
      "warn",
      { args: "none", caughtErrors: "none", ignoreRestSiblings: true },
    ],
    "eslint/no-useless-computed-key": "warn",
    "eslint/no-useless-concat": "warn",
    "eslint/no-useless-constructor": "warn",
    "eslint/no-useless-rename": "warn",
    "eslint/prefer-const": ["warn", { destructuring: "all" }],
    "eslint/sort-keys": ["warn", "asc", { allowLineSeparatedGroups: true, caseSensitive: true }],
    "eslint/unicode-bom": ["warn", "never"],
    "eslint/use-isnan": "error",
    "import/consistent-type-specifier-style": ["warn", "prefer-inline"],
    "import/default": "error",
    "import/export": "error",
    "import/exports-last": "off",
    "import/extensions": "off",
    "import/first": "warn",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/named": "error",
    "import/namespace": "error",
    "import/newline-after-import": ["warn", { count: 1 }],
    "import/no-absolute-path": "error",
    "import/no-amd": "error",
    "import/no-anonymous-default-export": "warn",
    "import/no-commonjs": "off",
    "import/no-cycle": "error",
    "import/no-default-export": "off",
    "import/no-duplicates": ["warn", { considerQueryString: true, preferInline: true }],
    "import/no-dynamic-require": "off",
    "import/no-empty-named-blocks": "warn",
    "import/no-mutable-exports": "error",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "off",
    "import/no-named-default": "off",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-self-import": "error",
    "import/no-unassigned-import": "off",
    "import/no-webpack-loader-syntax": "error",
    "import/prefer-default-export": "off",
    "import/unambiguous": "off",
    "react/jsx-boolean-value": "warn",
    "react/jsx-pascal-case": ["warn", { allowAllCaps: true }],
    "react/no-children-prop": "warn",
    "react/react-in-jsx-scope": "off",
    "react/rules-of-hooks": "warn",
    "react/style-prop-object": "warn",
  },
});
